title: Davide Testi
logo: /assets/img/headshot_circle.png
description: "QA at TikTok in the TECH team with MBA background in business consulting. Machine Learning & Data Engineering, certified from Université Paris 1 Panthéon-Sorbonne. 

  location: Verona, IT
  phone: (+39) 349-3371272
  email: davide.testi94@gmail.com
  linkedin: https://www.linkedin.com/in/davide-testi/
  portfolio_project: https://github.com/DavideTesti/mlproject

"
theme: jekyll-theme-minimal


