title: Davide Testi
logo: /assets/img/headshot_circle.png
description: "QA at TikTok in the TECH team with MBA background in business consulting. Machine Learning & Data Engineering, certified from Université Paris 1 Panthéon-Sorbonne. "
theme: jekyll-theme-minimal


